// <auto-generated />
namespace UserManagement_EF_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitialChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202207091930200_InitialChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
